### ISSUE TITLE
HOW do i install?

### ISSUE THREAD

**Issue by Christopalace01** [Anlominus/HacKingPro#1]
CheatSheets.md  HacKingPro  README.md
its showing just dis above..

so how do i install and run it?

**Comment by Anlominus** [comment]
### This tool does not currently have an installation.
### you know how Run it ?

**Comment by Anlominus** [comment]
Next time do not threaten me, I do not really care if you get along with him, but just to show you that I am different from you, I added an install button within the menu.
have fun :-)

Latest commit [4e1800d](https://github.com/Anlominus/HacKingPro/commit/4e1800dced5d4d6d67485655729a1495a875b911)

**Comment by Anlominus** [comment]
<img width="819" alt="image" src="https://user-images.githubusercontent.com/51442719/175462222-8ded57f3-0899-4a69-a16c-fb3e7c6d75d8.png">
