### ISSUE TITLE
Syntax error

### ISSUE THREAD

**Issue by allelive** [Anlominus/HacKingPro#14]
./HacKingPro: 122: Syntax error: "(" unexpected (expecting "}")

linux mint 20

**Comment by allelive** [comment]
ho installato zsh e quando corro: zsh HacKingPro
risultato: xDirectories:42: = not found 
quando corro: sh HacKingPro 
risultato: HacKingPro: 122: Syntax error: "(" unexpected (expecting "}")

**Comment by allelive** [comment]
perfetto grazie buona giornata e buon lavoro

**Comment by Anlominus** [comment]
Check last update maybe now it run
- [🐞 BugFix ✔️](https://github.com/Anlominus/HacKingPro/commit/683f70ea1062b58f4f4e454ac0fbe0c14839244b)

**Comment by allelive** [comment]
perfetto grazie ora funziona
